### ISSUE TITLE
Tweet thread from single text

### ISSUE THREAD

**Issue by Burwin** [BambooSoftwareLLC/twitter-auto-thread#2]
# Summary
Implement a simple client using `twitter-api-v2` that takes a bearer token for auth, and provides a method for tweeting a thread that is automatically broken up into tweets intelligently.

# Tasks
- [x] Wrap existing `TwitterApiReadWrite` client
- [x] Enable generating Tweet objects - split intelligently - from a single long text
- [x] Enable Tweeting a thread from a single long text
- [x] Enable Tweeting a thread from a series of tweet objects
